### ISSUE TITLE
how to analysis train json files

### ISSUE THREAD

**Issue by junqiangchen** [ibrahimethemhamamci/HierarchicalDet#5]
hi,
i don't know how to analysis train json files,can you share example code to analysis those files,such as,train_quadrant.json,train_quadrant_enumeration.json,train_quadrant_enumeration_disease.json
thank you!!

**Comment by sezginerr** [comment]
Hi,

Thank you for your interest in our dataset. Our implementation deviates from the standard COCO format as we use hierarchical labeling for our data. To utilize our approach for multi-class object detection, please follow these steps:

Install the  Detectron2 and PyCOCOtools libraries.
Replace the original library codes with our adjusted codes that we have provided in this GitHub repository.
Please note that our implementation requires three classes. Therefore, you should add "category_id2" and "category_id3" to the quadrant annotations in the "train_quadrant.json" file, and "category_id3" to the "train_quadrant_enumeration.json" file. You can assign these values as "None" so they will be ignored during the training process. 
Additionally, transfer the category names from the "quadrant-enumeration-disease.json" file to the other JSON files. Once you have completed these steps, you should be able to train your model using our implementation. 

If you prefer to use our dataset with a different model compatible with the COCO format, you can create single-class COCO JSON files by splitting the original JSON files for each class. If you require further assistance with adding "None" values or creating single-class COCO JSON files, please let us know, and we will gladly provide you with the relevant JSON parser codes. We will also add None-added (compatible with our framework) and splitted JSON files (standard single-class COCO JSONs) to GitHub repository for the DENTEX-challenge.

**Comment by junqiangchen** [comment]
@sezginerr hi,i want use segmentation model to detect，so i want to analysis json file，and convert it to mutil label mask，so i want know how to get those message

**Comment by sezginerr** [comment]
Hi @junqiangchen ,

Thank you for inquiring about our dataset. Yes, our dataset contains segmentation data in the RLE (Run Length Encoding) format, which is similar to the COCO dataset. You'll find that pycocotools can easily handle this RLE data without requiring any adjustments.

However, our current model is primarily designed for object detection and does not natively support training a instance segmentation model with multi-class labels. To modify the code for this purpose, please follow these steps:

1. Update the provided code to process segmentation data similarly to how we handle bounding box (bbox) information. This can be achieved with minor modifications to the pycocotools and detectron2 code snippets we've supplied.
2. If you prefer to handle each class for segmentation individually, simply separate the annotation files by class. The standard COCO format will remain compatible with your instance segmentation model in this scenario.
3. Alternatively, you may create a Python script to convert segmentation information from JSON files into 3-channel images if your goal is to implement a semantic segmentation model.

I hope this information is helpful in addressing your concerns. If you have any further questions or need clarification, please do not hesitate to ask.

**Comment by junqiangchen** [comment]
@sezginerr thank you,i have convert json type to segmentation mask successfully.

**Comment by wathoresanket** [comment]
> Hi,
> 
> Thank you for your interest in our dataset. Our implementation deviates from the standard COCO format as we use hierarchical labeling for our data. To utilize our approach for multi-class object detection, please follow these steps:
> 
> Install the Detectron2 and PyCOCOtools libraries. Replace the original library codes with our adjusted codes that we have provided in this GitHub repository. Please note that our implementation requires three classes. Therefore, you should add "category_id2" and "category_id3" to the quadrant annotations in the "train_quadrant.json" file, and "category_id3" to the "train_quadrant_enumeration.json" file. You can assign these values as "None" so they will be ignored during the training process. Additionally, transfer the category names from the "quadrant-enumeration-disease.json" file to the other JSON files. Once you have completed these steps, you should be able to train your model using our implementation.
> 
> If you prefer to use our dataset with a different model compatible with the COCO format, you can create single-class COCO JSON files by splitting the original JSON files for each class. If you require further assistance with adding "None" values or creating single-class COCO JSON files, please let us know, and we will gladly provide you with the relevant JSON parser codes. We will also add None-added (compatible with our framework) and splitted JSON files (standard single-class COCO JSONs) to GitHub repository for the DENTEX-challenge.

Hi, can you pls share the JSON codes?
