### ISSUE TITLE
diagnosis classes dataset problem

### ISSUE THREAD

**Issue by junqiangchen** [ibrahimethemhamamci/HierarchicalDet#6]
hi,
i find quadrant-enumeration-disease dataset ,only some teeth are marked with disease with label 0,1,2,3
Are the remaining unmarked teeth considered normal?
thankyou！

**Comment by sezginerr** [comment]
Hi @junqiangchen,

Yes, quadrant-enumeration-disease dataset only contains labels for diseased teeth. Healthy teeth are not labeled in that dataset. Please see fig 1 in our preprint "Diffusion-Based Hierarchical Multi-Label Object Detection to Analyze Panoramic Dental X-rays" for more information on the dataset labelling.

**Comment by junqiangchen** [comment]
@sezginerr thank you for explaining
